"""
ui/app.py — Streamlit Frontend for Architext

Run with:
    streamlit run ui/app.py
"""

from __future__ import annotations
import os
import sys
import time
import logging

# Make sure the project root is on the path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

# ── Page config (must be first Streamlit call) ───────────────────────────────
st.set_page_config(
    page_title="Architext — AI Solutions Architect",
    page_icon="🏗️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Styling ──────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .stApp { background-color: #0f1117; }
    .metric-card {
        background: #1e2130;
        border: 1px solid #2d3250;
        border-radius: 8px;
        padding: 16px;
        margin: 8px 0;
    }
    .risk-high { border-left: 4px solid #ff4b4b; }
    .risk-medium { border-left: 4px solid #ffa500; }
    .risk-low { border-left: 4px solid #00c851; }
    .score-bar {
        height: 8px;
        border-radius: 4px;
        background: linear-gradient(to right, #4f8ef7, #7c3aed);
    }
    .approach-card {
        background: #1a1d2e;
        border: 1px solid #2d3250;
        border-radius: 12px;
        padding: 20px;
    }
    .recommended-badge {
        background: linear-gradient(135deg, #4f8ef7, #7c3aed);
        color: white;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)


# ── Functions (defined BEFORE they're called) ─────────────────────────────────

def render_approach(approach: dict, is_recommended: bool = False):
    """Render a single architecture approach."""
    if is_recommended:
        st.markdown('<span class="recommended-badge">⭐ RECOMMENDED</span>', unsafe_allow_html=True)

    st.markdown(f"**{approach.get('summary', '')}**")

    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown("#### 🧩 Components")
        for comp in approach.get("components", []):
            cost = comp.get("estimated_monthly_cost_usd", 0)
            st.markdown(
                f"- **{comp.get('technology', '?')}** ({comp.get('type', '?')})  \n"
                f"  {comp.get('purpose', '')}  \n"
                f"  *~${cost:.0f}/mo*"
            )

        st.markdown("#### 🔄 Data Flow")
        st.markdown(approach.get("data_flow", ""))

    with col2:
        st.markdown("#### ⚖️ Trade-offs")
        for to in approach.get("trade_offs", []):
            st.markdown(f"**{to.get('category', '').title()}**")
            st.markdown(f"✅ {to.get('pro', '')}")
            st.markdown(f"❌ {to.get('con', '')}")

    # Scores visualization
    st.markdown("#### 📈 Scores")
    scores = approach.get("scores", {})
    score_cols = st.columns(len(scores))
    for col, (metric, score) in zip(score_cols, scores.items()):
        with col:
            st.metric(metric.replace("_", " ").title(), f"{score}/10")

    # Mermaid diagram
    diagram = approach.get("mermaid_diagram", "")
    if diagram:
        st.markdown("#### 🗺️ Architecture Diagram")
        #try:
        #    from streamlit_mermaid import st_mermaid
        #    st_mermaid(diagram, height=400)
        #except ImportError:
        st.code(diagram, language="text")
        st.caption("📌 Paste this at [mermaid.live](https://mermaid.live) to render the diagram")

    total = approach.get("total_monthly_cost_usd", 0)
    st.metric("Total Estimated Monthly Cost", f"${total:.0f}/mo")


def generate_markdown_report(state: dict, report: dict) -> str:
    """Generate a clean markdown report for download."""
    recommended = report.get("recommended", {})
    constraints = state.get("constraints", {})

    lines = [
        f"# Architecture Report: {state.get('use_case_summary', 'Untitled Project')}",
        f"\n*Generated by Architext*\n",
        f"## Executive Summary",
        f"\n{report.get('summary', '')}\n",
        f"## Project Details",
        f"- **Scale:** {constraints.get('scale_users', 'N/A')} users",
        f"- **Budget:** ${constraints.get('budget_monthly_usd', 'N/A')}/mo",
        f"- **Team Size:** {constraints.get('team_size', 'N/A')} engineers",
        f"- **Compliance:** {', '.join(constraints.get('compliance', [])) or 'None'}",
        f"\n## Recommended Architecture: {recommended.get('name', '')}",
        f"\n{recommended.get('summary', '')}\n",
        f"### Components",
    ]

    for comp in recommended.get("components", []):
        lines.append(f"- **{comp.get('technology')}** ({comp.get('type')}): {comp.get('purpose')} — ~${comp.get('estimated_monthly_cost_usd', 0):.0f}/mo")

    lines += [
        f"\n### Architecture Diagram",
        f"\n```mermaid\n{recommended.get('mermaid_diagram', '')}\n```\n",
        f"## Comparison Matrix",
        f"\n{report.get('comparison_table', '')}\n",
        f"## Risk Assessment",
    ]

    for risk in report.get("risk_assessment", []):
        lines.append(f"\n### [{risk.get('severity', '').upper()}] {risk.get('area', '').title()}")
        lines.append(f"**Issue:** {risk.get('description', '')}")
        lines.append(f"**Mitigation:** {risk.get('mitigation', '')}")

    lines += [f"\n## Next Steps"]
    for i, step in enumerate(report.get("next_steps", []), 1):
        lines.append(f"{i}. {step}")

    return "\n".join(lines)


def render_report(state, report):
    """Render the full architecture report in Streamlit."""
    st.divider()

    # ── Header ──────────────────────────────────────────────────────────────
    recommended = report.get("recommended", {})
    st.markdown(f"## 📋 Architecture Analysis: {state.get('use_case_summary', '')}")

    # Key stats
    cols = st.columns(4)
    constraints = state.get("constraints", {})
    with cols[0]:
        st.metric("Scale", f"{constraints.get('scale_users', 'N/A'):,}" if constraints.get('scale_users') else "N/A", "users")
    with cols[1]:
        st.metric("Est. Cost", f"${recommended.get('total_monthly_cost_usd', 0):.0f}/mo")
    with cols[2]:
        st.metric("Recommended", recommended.get("name", "N/A"))
    with cols[3]:
        compliance = constraints.get("compliance", [])
        st.metric("Compliance", ", ".join(compliance) if compliance else "None")

    # ── Executive Summary ────────────────────────────────────────────────────
    st.markdown("### 📝 Executive Summary")
    st.markdown(report.get("summary", ""))

    # ── Architecture Approaches ───────────────────────────────────────────────
    st.markdown("### 🏗️ Architecture Approaches")

    approaches = [recommended] + report.get("alternatives", [])
    tabs = st.tabs([
        f"{'⭐ ' if i == 0 else ''}{a.get('name', f'Option {i+1}')}"
        for i, a in enumerate(approaches)
    ])

    for i, (tab, approach) in enumerate(zip(tabs, approaches)):
        with tab:
            render_approach(approach, is_recommended=(i == 0))

    # ── Comparison Table ─────────────────────────────────────────────────────
    st.markdown("### 📊 Comparison Matrix")
    st.markdown(report.get("comparison_table", ""))

    # ── Risk Assessment ──────────────────────────────────────────────────────
    risks = report.get("risk_assessment", [])
    if risks:
        st.markdown("### ⚠️ Risk Assessment")
        for risk in risks:
            severity = risk.get("severity", "medium")
            color = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(severity, "🟡")
            with st.expander(f"{color} [{severity.upper()}] {risk.get('area', '').title()} — {risk.get('description', '')[:80]}..."):
                st.markdown(f"**Description:** {risk.get('description', '')}")
                st.markdown(f"**Mitigation:** {risk.get('mitigation', '')}")

    # ── Next Steps ────────────────────────────────────────────────────────────
    next_steps = report.get("next_steps", [])
    if next_steps:
        st.markdown("### 🚀 Recommended Next Steps")
        for i, step in enumerate(next_steps, 1):
            st.markdown(f"**{i}.** {step}")

    # ── Export ────────────────────────────────────────────────────────────────
    st.divider()
    markdown_report = generate_markdown_report(state, report)
    st.download_button(
        label="📥 Download Report (Markdown)",
        data=markdown_report,
        file_name=f"architecture_report_{int(time.time())}.md",
        mime="text/markdown",
    )


# ── Sidebar: Configuration ────────────────────────────────────────────────────
with st.sidebar:
    st.title("⚙️ Configuration")

    ollama_url = st.text_input(
        "Ollama URL",
        value=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
        help="URL where Ollama is running",
    )

    model_name = st.selectbox(
        "Model",
        options=["llama3.2", "llama3.1", "llama3", "mistral", "codellama"],
        index=0,
        help="Ollama model to use. llama3.2 recommended.",
    )

    st.divider()
    st.markdown("### 🔧 Setup")
    if st.button("🗄️ Initialize Knowledge Base", use_container_width=True):
        with st.spinner("Ingesting knowledge base..."):
            try:
                from rag.ingest import ingest_knowledge_base
                count = ingest_knowledge_base(force_reload=True)
                st.success(f"✅ Loaded {count} knowledge chunks")
            except Exception as e:
                st.error(f"Failed: {e}")


# ── Main UI ──────────────────────────────────────────────────────────────────
st.title("🏗️ Architext")
st.markdown("**AI Solutions Architect** — Transform requirements into production-ready architecture decisions")

# Input area
user_input = st.text_area(
    "Describe your project",
    value=st.session_state.get("example_prompt", ""),
    height=150,
    placeholder="Describe what you want to build. Include: what it does, how many users, team size, budget, timeline, compliance requirements, existing tech stack if any...",
    help="The more context you provide, the better the recommendations.",
)

# Clear example after use
if "example_prompt" in st.session_state:
    del st.session_state["example_prompt"]

col1, col2 = st.columns([1, 5])
with col1:
    run_btn = st.button("🚀 Analyze", type="primary", use_container_width=True)
with col2:
    if run_btn and not user_input.strip():
        st.warning("Please describe your project first.")

# ── Run Agent ────────────────────────────────────────────────────────────────
if run_btn and user_input.strip():
    progress_placeholder = st.empty()
    status_placeholder = st.empty()

    steps = [
        ("🔍 Extracting requirements...", 0.15),
        ("📚 Querying knowledge base...", 0.35),
        ("🏗️ Generating architecture approaches...", 0.75),
        ("📊 Synthesizing report...", 0.95),
    ]

    progress = progress_placeholder.progress(0.0)

    try:
        from agent.graph import run_agent

        for msg, val in steps[:1]:
            status_placeholder.info(msg)
            progress.progress(val)

        import threading
        result = {}
        error = {}

        def _run():
            try:
                state = run_agent(
                    user_input=user_input,
                    ollama_base_url=ollama_url,
                    model_name=model_name,
                )
                result["state"] = state
            except Exception as e:
                error["msg"] = str(e)

        thread = threading.Thread(target=_run)
        thread.start()

        step_idx = 1
        elapsed = 0
        while thread.is_alive():
            time.sleep(2)
            elapsed += 2
            if step_idx < len(steps):
                if elapsed > 15 * step_idx:
                    msg, val = steps[step_idx]
                    status_placeholder.info(f"{msg} ({elapsed}s elapsed)")
                    progress.progress(val)
                    step_idx += 1

        thread.join()

        if error:
            st.error(f"Agent error: {error['msg']}")
            st.stop()

        state = result["state"]
        progress.progress(1.0)
        status_placeholder.success("✅ Analysis complete!")
        time.sleep(0.5)
        progress_placeholder.empty()
        status_placeholder.empty()

        # ── Handle clarifications needed ──────────────────────────────────
        if state.get("needs_clarification") and not state.get("report"):
            st.warning("### 💬 A few clarifying questions before I proceed:")
            clarifications = {}
            for q in state.get("clarifications_needed", []):
                clarifications[q] = st.text_input(q)
            if st.button("Continue with clarifications"):
                state = run_agent(
                    user_input=user_input,
                    clarifications=clarifications,
                    ollama_base_url=ollama_url,
                    model_name=model_name,
                )

        # ── Render Report ─────────────────────────────────────────────────
        report = state.get("report")
        if not report:
            st.error("No report generated. Check that Ollama is running and the model is pulled.")
            if state.get("error"):
                st.code(state["error"])
            st.stop()

        st.session_state['current_state'] = state
        st.session_state['current_report'] = report
        st.session_state['has_report'] = True
        
        render_report(state, report)

    except ImportError as e:
        st.error(f"Import error: {e}")
        st.markdown("**Make sure to install dependencies:** `pip install -r requirements.txt`")
    except Exception as e:
        progress_placeholder.empty()
        status_placeholder.empty()
        st.error(f"Error running agent: {e}")
        st.exception(e)
        